### ISSUE TITLE
Валится на определенных вхождениях

### ISSUE THREAD

**Issue by robhrt7** [afelix/setochka#13]
1. Валится на хаке для ие "//":

``` css
.class {//color:red;}
```

без ошибки.
1. Валится на фильтрах

``` css
.class {
filter: progid:DXImageTransform.Microsoft.AlphaImageLoader(src =/res/default/Images/prompt_yellow.png, sizingMethod = crop);
}
```

с ошибкой 

```
Rule: filterp not found!
Trace
    at CSSTranslator.invoke (/usr/local/lib/node_modules/setochka/node_modules/cssp/node_modules/ometajs/lib/ometajs/core/grammar.js:159:15)
    at CSSTranslator.cache [as _cache] (/usr/local/lib/node_modules/setochka/node_modules/cssp/node_modules/ometajs/lib/ometajs/core/parser.js:123:16)
    at CSSTranslator._invoke (/usr/local/lib/node_modules/setochka/node_modules/cssp/node_modules/ometajs/lib/ometajs/core/grammar.js:168:17)
    at CSSTranslator.rule [as _rule] (/usr/local/lib/node_modules/setochka/node_modules/cssp/node_modules/ometajs/lib/ometajs/core/grammar.js:269:16)
    at Function.matchAll (/usr/local/lib/node_modules/setochka/node_modules/cssp/node_modules/ometajs/lib/ometajs/core/grammar.js:60:13)
    at Function.match (/usr/local/lib/node_modules/setochka/node_modules/cssp/node_modules/ometajs/lib/ometajs/core/grammar.js:36:15)
    at Object.exports.translate (/usr/local/lib/node_modules/setochka/node_modules/cssp/lib/csspapi.js:18:56)
    at translateBlock (/usr/local/lib/node_modules/setochka/lib/setochka.js:193:22)
    at extractFromBlock (/usr/local/lib/node_modules/setochka/lib/setochka.js:146:18)
    at extractFromTree (/usr/local/lib/node_modules/setochka/lib/setochka.js:79:28)
    at Object.<anonymous> (/usr/local/lib/node_modules/setochka/lib/setochka.js:33:9)

/usr/local/lib/node_modules/setochka/node_modules/cssp/node_modules/ometajs/lib/ometajs/core/grammar.js:74
  if (!errback) errback = function (err) { throw err; };
                                                 ^
Error: filterp rule failed at: [ [ 'property', [ 'ident', '_filter' ] ] ]:0
    at CSSTranslator.getError [as _getError] (/usr/local/lib/node_modules/setochka/node_modules/cssp/node_modules/ometajs/lib/ometajs/core/grammar.js:81:37)
    at Function.matchAll (/usr/local/lib/node_modules/setochka/node_modules/cssp/node_modules/ometajs/lib/ometajs/core/grammar.js:61:17)
    at Function.match (/usr/local/lib/node_modules/setochka/node_modules/cssp/node_modules/ometajs/lib/ometajs/core/grammar.js:36:15)
    at Object.exports.translate (/usr/local/lib/node_modules/setochka/node_modules/cssp/lib/csspapi.js:18:56)
    at translateBlock (/usr/local/lib/node_modules/setochka/lib/setochka.js:193:22)
    at extractFromBlock (/usr/local/lib/node_modules/setochka/lib/setochka.js:146:18)
    at extractFromTree (/usr/local/lib/node_modules/setochka/lib/setochka.js:79:28)
    at Object.<anonymous> (/usr/local/lib/node_modules/setochka/lib/setochka.js:33:9)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
```
1. Валится на ошибках в стилях

``` css
.class{color:red:}
{display: none;}
```

с ошибкой

```
TypeError: Cannot read property 'length' of undefined
    at translateBlock (/usr/local/lib/node_modules/setochka/lib/setochka.js:186:30)
    at extractFromBlock (/usr/local/lib/node_modules/setochka/lib/setochka.js:146:18)
    at extractFromTree (/usr/local/lib/node_modules/setochka/lib/setochka.js:79:28)
    at Object.<anonymous> (/usr/local/lib/node_modules/setochka/lib/setochka.js:33:9)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Function.Module.runMain (module.js:497:10)
    at startup (node.js:119:16)
```

Ладно что валится на ошибках в стилях, но нигде это не показывает, а в некоторых случаях валится без ошибки и вообще не понятно, что не все работает как надо, просто до проблемного места стили парсятся, а дальше нет.

**Comment by afelix** [comment]
@operatino Обновил парсер, теперь не должно валиться на правильных стилях. На ошибочных всё ещё валится. Опубликовал v0.0.6.
